name: Docker Image CI for GHCR

on:
    push

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: npm install
              run: npm ci
            - name: run the unit tests
              run: npm test
            - name: Publish the image to github container registry
              run: |
                docker login --username kylecoding --password ${{secrets.ACCESS_TOKEN}} ghcr.io
                docker build -t ghcr.io/kylecoding/arithmetic-service:1 --file Dockerfile .
                docker push ghcr.io/kylecoding/arithmetic-service:1
            - name: Publish the image to azure container registry
              run: | 
                docker login --username practicum7Reg --password ${{secrets.AZURE_CONTAINER_REGISTRY}} practicum7Reg.azurecr.io
                docker tag ghcr.io/kylecoding/arithmetic-service:1 practicum7Reg.azurecr.io/arithmetic-service:1
                docker push practicum7Reg.azurecr.io/arithmetic-service:1