name: Docker Image CI for GHCR

on:
  push:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{github.sha}}
      CONTAINER_REGISTRY: ${{secrets.AZURE_CONTAINER_REGISTRY}}
      CONTAINER_REGISTRY_UN: ${{secrets.CONTAINER_REGISTRY_UN}}
      CONTAINER_REGISTRY_PW: ${{secrets.CONTAINER_REGISTRY_PW}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build the package (no tests)
        run: mvn --batch-mode -DskipTests package
      - name: Run the unit tests
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
      - name: Report test results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
      - name: Publish the image to github container registry
        run: |
          docker login --username kyleLissCoding --password ${{secrets.ACCESS_TOKEN}} ghcr.io
          docker build -t ghcr.io/kylelisscoding/arithmetic-service:$VERSION --file Dockerfile .
          docker push ghcr.io/kylelisscoding/arithmetic-service:$VERSION
      - name: Publish the image to azure container registry
        run: | 
          docker login --username $CONTAINER_REGISTRY_UN --password $CONTAINER_REGISTRY_PW $CONTAINER_REGISTRY
          docker tag ghcr.io/kylelisscoding/arithmetic-service:$VERSION $CONTAINER_REGISTRY/arithmetic-service:$VERSION
          docker push $CONTAINER_REGISTRY/arithmetic-service:$VERSION

        # Installs Kubectl and connects it to the cluster
      - uses: tale/kubectl-action@v1
        with:
            base64-kube-config: ${{secrets.KUBE_CONFIG}}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set execute permissions for deploy.sh
        run: chmod +x ./scripts/deploy.sh

      - name: Deploy
        run: ./scripts/deploy.sh